/* src\Components\Sidebar\ProgressOptions.svelte generated by Svelte v3.29.7 */
import {
	SvelteComponent,
	append,
	attr,
	component_subscribe,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	listen,
	mount_component,
	run_all,
	safe_not_equal,
	set_input_value,
	space,
	to_number,
	transition_in,
	transition_out
} from "../../../web_modules/svelte/internal.js";

import DropDown from "./DropDown.js";
import { projectStore } from "../../JS/stores/project.js";
import { progressBarSize } from "../../JS/stores/progressBar.js";

function create_if_block(ctx) {
	let div2;
	let div0;
	let label0;
	let t1;
	let input0;
	let input0_min_value;
	let input0_max_value;
	let t2;
	let div1;
	let label1;
	let t4;
	let input1;
	let mounted;
	let dispose;

	return {
		c() {
			div2 = element("div");
			div0 = element("div");
			label0 = element("label");
			label0.textContent = "number of bars";
			t1 = space();
			input0 = element("input");
			t2 = space();
			div1 = element("div");
			label1 = element("label");
			label1.textContent = "show percentage value";
			t4 = space();
			input1 = element("input");
			attr(label0, "for", "bars");
			attr(label0, "class", "flex-1 text-xs text-left");
			attr(input0, "type", "number");
			attr(input0, "id", "bars");
			attr(input0, "min", input0_min_value = progressBarSize.min);
			attr(input0, "max", input0_max_value = progressBarSize.max);
			attr(input0, "class", "w-16 text-xs h-5 pl-1 rounded-sm bg-gray-50 border border-sidebar-border");
			attr(div0, "id", "barsInput");
			attr(div0, "class", "w-full flex flex-row items-center");
			attr(label1, "for", "showPerc");
			attr(label1, "class", "text-xs text-left pr-3");
			attr(input1, "id", "showPerc");
			attr(input1, "type", "checkbox");
			attr(div1, "id", "checkbox");
			attr(div1, "class", "w-full flex flex-row pt-2 justify-between items-center");
			attr(div2, "id", "options");
			attr(div2, "class", "w-full flex flex-col items-start pt-3 font-semibold text-gray-700");
		},
		m(target, anchor) {
			insert(target, div2, anchor);
			append(div2, div0);
			append(div0, label0);
			append(div0, t1);
			append(div0, input0);
			set_input_value(input0, /*$projectStore*/ ctx[0].sizeOfProgressBar);
			append(div2, t2);
			append(div2, div1);
			append(div1, label1);
			append(div1, t4);
			append(div1, input1);
			input1.checked = /*$projectStore*/ ctx[0].showProgressPercentage;

			if (!mounted) {
				dispose = [
					listen(input0, "input", /*input0_input_handler*/ ctx[3]),
					listen(input1, "change", /*input1_change_handler*/ ctx[4])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty & /*$projectStore*/ 1 && to_number(input0.value) !== /*$projectStore*/ ctx[0].sizeOfProgressBar) {
				set_input_value(input0, /*$projectStore*/ ctx[0].sizeOfProgressBar);
			}

			if (dirty & /*$projectStore*/ 1) {
				input1.checked = /*$projectStore*/ ctx[0].showProgressPercentage;
			}
		},
		d(detaching) {
			if (detaching) detach(div2);
			mounted = false;
			run_all(dispose);
		}
	};
}

function create_fragment(ctx) {
	let div1;
	let div0;
	let h1;
	let t1;
	let dropdown;
	let t2;
	let current;
	let mounted;
	let dispose;

	dropdown = new DropDown({
			props: {
				menuDisplayed: /*$projectStore*/ ctx[0].showProgressOptions,
				toggleSubMenu: /*func*/ ctx[2]
			}
		});

	let if_block = /*$projectStore*/ ctx[0].showProgressOptions && create_if_block(ctx);

	return {
		c() {
			div1 = element("div");
			div0 = element("div");
			h1 = element("h1");
			h1.textContent = "PROGRESS BAR OPTIONS";
			t1 = space();
			create_component(dropdown.$$.fragment);
			t2 = space();
			if (if_block) if_block.c();
			attr(h1, "class", "w-full text-left font-semibold cursor-pointer select-none");
			attr(div0, "id", "header");
			attr(div0, "class", "w-full flex flex-row");
			attr(div1, "id", "progressOptions");
			attr(div1, "class", "w-full text-xs flex flex-col justify-start border-t border-b border-black px-3 py-3 select-none");
		},
		m(target, anchor) {
			insert(target, div1, anchor);
			append(div1, div0);
			append(div0, h1);
			append(div0, t1);
			mount_component(dropdown, div0, null);
			append(div1, t2);
			if (if_block) if_block.m(div1, null);
			current = true;

			if (!mounted) {
				dispose = listen(h1, "click", /*click_handler*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			const dropdown_changes = {};
			if (dirty & /*$projectStore*/ 1) dropdown_changes.menuDisplayed = /*$projectStore*/ ctx[0].showProgressOptions;
			dropdown.$set(dropdown_changes);

			if (/*$projectStore*/ ctx[0].showProgressOptions) {
				if (if_block) {
					if_block.p(ctx, dirty);
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					if_block.m(div1, null);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}
		},
		i(local) {
			if (current) return;
			transition_in(dropdown.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(dropdown.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div1);
			destroy_component(dropdown);
			if (if_block) if_block.d();
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $projectStore;
	component_subscribe($$self, projectStore, $$value => $$invalidate(0, $projectStore = $$value));

	const click_handler = () => {
		projectStore.toggleProgressMenu();
	};

	const func = () => {
		projectStore.toggleProgressMenu();
	};

	function input0_input_handler() {
		$projectStore.sizeOfProgressBar = to_number(this.value);
		projectStore.set($projectStore);
	}

	function input1_change_handler() {
		$projectStore.showProgressPercentage = this.checked;
		projectStore.set($projectStore);
	}

	return [
		$projectStore,
		click_handler,
		func,
		input0_input_handler,
		input1_change_handler
	];
}

class ProgressOptions extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default ProgressOptions;